# Generated by Django 5.1.3 on 2025-01-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theses', '0003_thesisprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feedback', models.TextField()),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('thesis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='theses.thesis')),
            ],
        ),
    ]
